services:
    voice:
        build:
            context: ../..
            dockerfile: apps/voice/Dockerfile
        env_file: .env
        ports:
            - "3030:3030"
            - "40000-40100:40000-40100/udp"
            - "40000-40100:40000-40100/tcp"
        networks:
            - dokploy-network
        restart: unless-stopped

networks:
    dokploy-network:
        external: true
