services:
    voice:
        build:
            context: ../..
            dockerfile: apps/voice/Dockerfile
        env_file: .env
        ports:
            - "3030:3030"
            - "40000-49999:40000-49999/udp"
            - "40000-49999:40000-49999/tcp"
        restart: unless-stopped
